// Package migration deterministically projects closed-list protocol sections into
// CDL declarations. It extracts structure only; it never authors semantics. The
// checked-in output is verified byte-for-byte against a fresh extraction.
package migration

import (
	"fmt"
	"github.com/nckirik/legacy-autopsy/cdl"
	"regexp"
	"strings"

	"github.com/nckirik/legacy-autopsy/internal/markdown"
)

// GeneratorVersion identifies the extraction rules.
const GeneratorVersion = "internal/migration/3"

// EnumDomain is one closed finite-choice domain.
type EnumDomain struct {
	ID     string
	Path   string
	Values []string
}

// StatusTaxonomy is the §5.1 extraction result.
type StatusTaxonomy struct {
	Body         string
	PrefixGroups []EnumDomain
	Registry     []EnumDomain
}

var (
	prefixToken    = regexp.MustCompile("`(\\[[A-Z]-[A-Z-]+\\])`")
	statusSection  = "5.1. Dedicated prefix groups"
	registryAnchor = "Preflight.Current Iteration"
)

// ExtractStatusTaxonomy parses the §5.1 prefix groups and the exhaustive
// finite-enum registry from the protocol AST.
func ExtractStatusTaxonomy(doc *markdown.Document) (StatusTaxonomy, error) {
	nodes, err := doc.Section(statusSection)
	if err != nil {
		return StatusTaxonomy{}, err
	}
	var taxonomy StatusTaxonomy
	if text, err := doc.SectionText(statusSection); err == nil {
		lines := strings.Split(strings.TrimRight(text, "\n"), "\n")
		if len(lines) > 1 {
			lines = lines[1:]
		}
		for len(lines) > 0 && strings.TrimSpace(lines[0]) == "" {
			lines = lines[1:]
		}
		for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
			lines = lines[:len(lines)-1]
		}
		taxonomy.Body = strings.Join(lines, "\n")
	}
	for i, node := range nodes {
		if node.Kind != markdown.Heading || node.Level != 3 {
			continue
		}
		heading := node.Text
		if strings.Contains(strings.ToLower(heading), "finite-enum") {
			continue
		}
		values := []string{}
		seen := map[string]bool{}
		for j := i + 1; j < len(nodes); j++ {
			if nodes[j].Kind == markdown.Heading && nodes[j].Level <= 3 {
				break
			}
			content := nodes[j].Raw + " " + nodes[j].Text
			for _, match := range prefixToken.FindAllStringSubmatch(content, -1) {
				if !seen[match[1]] {
					seen[match[1]] = true
					values = append(values, match[1])
				}
			}
		}
		if len(values) == 0 {
			return StatusTaxonomy{}, fmt.Errorf("prefix group %q has no bracketed tokens", heading)
		}
		label := heading
		if idx := strings.Index(heading, " ("); idx > 0 {
			label = heading[:idx]
		}
		taxonomy.PrefixGroups = append(taxonomy.PrefixGroups, EnumDomain{
			ID: "PREFIX-" + UpperSlug(label), Path: heading, Values: values,
		})
	}
	if len(taxonomy.PrefixGroups) != 7 {
		return StatusTaxonomy{}, fmt.Errorf("found %d prefix groups, want 7", len(taxonomy.PrefixGroups))
	}

	for _, node := range nodes {
		if node.Kind != markdown.CodeBlock || !strings.Contains(node.Raw, registryAnchor) {
			continue
		}
		for _, line := range strings.Split(node.Raw, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || !strings.Contains(line, "->") {
				continue
			}
			parts := strings.SplitN(line, "->", 2)
			path := strings.TrimSpace(parts[0])
			valuePart := strings.TrimSpace(parts[1])
			if path == "" || strings.Contains(valuePart, "§") {
				continue
			}
			var values []string
			for _, value := range strings.Split(valuePart, "|") {
				value = strings.TrimSpace(value)
				if value != "" {
					values = append(values, value)
				}
			}
			if len(values) == 0 {
				return StatusTaxonomy{}, fmt.Errorf("registry path %q has no values", path)
			}
			taxonomy.Registry = append(taxonomy.Registry, EnumDomain{
				ID: "REGISTRY-" + UpperSlug(path), Path: path, Values: values,
			})
		}
	}
	if len(taxonomy.Registry) < 100 {
		return StatusTaxonomy{}, fmt.Errorf("found %d registry paths, want at least 100", len(taxonomy.Registry))
	}
	return taxonomy, nil
}

// RenderStatusTaxonomy renders the generated §5.1 CDL section.
func RenderStatusTaxonomy(t StatusTaxonomy, sourceFingerprint string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# GENERATED by %s from the frozen protocol oracle %s - do not hand-edit\n", GeneratorVersion, sourceFingerprint)
	b.WriteString("PART status-evidence \"Status Taxonomy and Evidence\"\n\n")
	b.WriteString("SECTION status-taxonomy\n")
	b.WriteString("TITLE \"Dedicated prefix groups\"\n\n")
	b.WriteString("GOAL\n")
	if t.Body != "" {
		b.WriteString(t.Body)
		b.WriteString("\n")
	} else {
		b.WriteString("  Finite protocol enums MUST be validated from the normative Markdown AST.\n")
	}
	b.WriteString("END\n\n")
	b.WriteString("RULE finite-enum-registry\n")
	b.WriteString("  GOAL\n")
	b.WriteString("    The exhaustive registry of all normative finite-choice scalar and table-cell\n")
	b.WriteString("    paths is declared as ENUM domains in this section. Aliases, invented labels,\n")
	b.WriteString("    inherited enums, and applying one schema's label map to another schema are\n")
	b.WriteString("    forbidden unless explicitly introduced by a protocol/schema version. An\n")
	b.WriteString("    undeclared finite-enum path is a validation error rather than permission to\n")
	b.WriteString("    infer an enum from its label or token.\n")
	b.WriteString("  END\n")
	b.WriteString("END\n\n")
	b.WriteString("RULE traversal-matrix-status\n")
	b.WriteString("  GOAL\n")
	b.WriteString("    EntryCluster.Required Traversal Matrix[].Status accepts N/A if and only if the\n")
	b.WriteString("    same row's Applicability is exactly Not-Applicable; such a row MUST carry the\n")
	b.WriteString("    claim-backed reason required by §3.1. A Required row MUST use one bracketed\n")
	b.WriteString("    allowed R- token and MUST NOT use N/A. A Not-Applicable row MUST use exactly\n")
	b.WriteString("    N/A and MUST NOT use an R- token.\n")
	b.WriteString("  END\n")
	b.WriteString("END\n")
	renderDomains(&b, t.PrefixGroups)
	renderDomains(&b, t.Registry)
	text := b.String()
	if formatted, diags := cdl.FormatSource("protocol/status-taxonomy.cdl", []byte(text)); len(diags) == 0 {
		return string(formatted)
	}
	return text
}

func renderDomains(b *strings.Builder, domains []EnumDomain) {
	for _, domain := range domains {
		fmt.Fprintf(b, "\nENUM %s\n", domain.ID)
		for _, value := range domain.Values {
			fmt.Fprintf(b, "  %s\n", value)
		}
		b.WriteString("END\n")
	}
}

// UpperSlug lowercases and joins alphanumeric runs with hyphens, uppercased:
// "ExitECandidateReport.Check Results[].Result" -> "EXITECANDIDATEREPORT-CHECK-RESULTS-RESULT".
func UpperSlug(value string) string {
	return strings.ToUpper(Slug(value))
}

// Slug lowercases and joins alphanumeric runs with hyphens.
func Slug(value string) string {
	var b strings.Builder
	pendingHyphen := false
	for _, r := range strings.ToLower(value) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			if pendingHyphen && b.Len() > 0 {
				b.WriteByte('-')
			}
			pendingHyphen = false
			b.WriteRune(r)
		default:
			pendingHyphen = true
		}
	}
	return b.String()
}
