package cdl

import (
	"fmt"
	"strings"
)

// Provenance is the declared generation context for a projection. GeneratedAt is
// an explicit input, never the wall clock.
type Provenance struct {
	SourcePath        string
	SourceFingerprint string
	EIRHash           string
	GeneratedAt       string
}

// RenderPrompt renders one projection for one channel from EIR. The renderer is
// template-total: every operation form in the frozen pilot subset has a template,
// and anything else is an error rather than improvised wording.
func RenderPrompt(doc *EIRDoc, projectionID, channel string, prov Provenance) ([]byte, error) {
	proj, ok := findProjection(doc, projectionID)
	if !ok {
		return nil, cdlerr("CDL_RENDER_UNSUPPORTED", "projection %s not found", projectionID)
	}
	supported := false
	for _, ch := range proj.Channels {
		if ch == channel {
			supported = true
		}
	}
	if !supported {
		return nil, cdlerr("CDL_RENDER_UNSUPPORTED", "projection %s does not support channel %s", projectionID, channel)
	}
	sec, ok := coveredSection(doc, proj)
	if !ok {
		return nil, cdlerr("CDL_RENDER_UNSUPPORTED", "projection %s covers no section", projectionID)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- GENERATED by %s - do not edit\n", doc.Envelope.Generator)
	fmt.Fprintf(&b, "     language: %s  stdlib: %s  renderer: %s\n", doc.Envelope.Language, doc.Envelope.Stdlib, doc.Envelope.Generator)
	fmt.Fprintf(&b, "     source: %s %s\n", prov.SourcePath, prov.SourceFingerprint)
	fmt.Fprintf(&b, "     eir: %s\n", prov.EIRHash)
	fmt.Fprintf(&b, "     projection-format: %d  channel: %s\n", doc.Envelope.EIRFormat, channel)
	fmt.Fprintf(&b, "     generated-at: %s -->\n\n", prov.GeneratedAt)
	fmt.Fprintf(&b, "# %s (§%s)\n\n", sec.Title, sec.Number)
	fmt.Fprintf(&b, "%s\n", sec.Goal)
	for _, step := range sec.Steps {
		if omittedFor(proj, step.ID, channel) {
			continue
		}
		text, ok := proj.StepTexts[step.ID]
		if !ok {
			var err error
			text, err = renderStep(step, proj.RuleTexts)
			if err != nil {
				return nil, err
			}
		}
		fmt.Fprintf(&b, "\n- **%s** — %s", step.ID, text)
	}
	b.WriteString("\n")
	return []byte(b.String()), nil
}

func findProjection(doc *EIRDoc, id string) (EIRProjection, bool) {
	for _, p := range doc.Projections {
		if p.ID == id {
			return p, true
		}
	}
	return EIRProjection{}, false
}

func coveredSection(doc *EIRDoc, proj EIRProjection) (EIRSection, bool) {
	for _, s := range doc.Sections {
		if proj.Covers == "" || s.ID == proj.Covers {
			return s, true
		}
	}
	return EIRSection{}, false
}

func omittedFor(proj EIRProjection, stepID, channel string) bool {
	for _, om := range proj.Omissions {
		if om.Step != stepID {
			continue
		}
		if len(om.Channels) == 0 {
			return true
		}
		for _, ch := range om.Channels {
			if ch == channel {
				return true
			}
		}
	}
	return false
}

func renderStep(step EIRStep, ruleTexts map[string]string) (string, error) {
	if step.Owner == "AGENT" {
		return step.Require, nil
	}
	return renderOps(step.Ops, ruleTexts)
}

func renderOps(ops []map[string]any, ruleTexts map[string]string) (string, error) {
	var parts []string
	for _, op := range ops {
		switch {
		case op["requires"] != nil:
			continue
		case op["set"] != nil:
			m := op["set"].(map[string]any)
			text, err := exprText(m["value"], ruleTexts)
			if err != nil {
				return "", err
			}
			parts = append(parts, fmt.Sprintf("Set `%v` to %s.", m["target"], text))
		case op["let"] != nil:
			m := op["let"].(map[string]any)
			text, err := exprText(m["value"], ruleTexts)
			if err != nil {
				return "", err
			}
			parts = append(parts, fmt.Sprintf("Bind `%v` to %s.", m["target"], text))
		case op["append"] != nil:
			m := op["append"].(map[string]any)
			parts = append(parts, fmt.Sprintf("append a `%v` row to `%v`.", m["row-type"], m["to"]))
		case op["foreach"] != nil:
			m := op["foreach"].(map[string]any)
			body, err := renderOps(toOpMapSlice(m["do"]), ruleTexts)
			if err != nil {
				return "", err
			}
			parts = append(parts, fmt.Sprintf("For each `%v` in `%v`, %s", m["var"], m["in"], body))
		case op["guard"] != nil:
			m := op["guard"].(map[string]any)
			text, err := exprText(m["expr"], ruleTexts)
			if err != nil {
				return "", err
			}
			otherwise := toOpMapSlice(m["otherwise"])
			effect, err := renderOps(otherwise, ruleTexts)
			if err != nil {
				return "", err
			}
			parts = append(parts, fmt.Sprintf("If it is not the case that %s, %s", text, effect))
		case op["if"] != nil:
			m := op["if"].(map[string]any)
			cond, err := exprText(m["cond"], ruleTexts)
			if err != nil {
				return "", err
			}
			then, err := renderOps(toOpMapSlice(m["then"]), ruleTexts)
			if err != nil {
				return "", err
			}
			els, err := renderOps(toOpMapSlice(m["else"]), ruleTexts)
			if err != nil {
				return "", err
			}
			parts = append(parts, fmt.Sprintf("If %s, then %s; otherwise %s.",
				cond, lowerFirst(strings.TrimSuffix(strings.TrimSpace(then), ".")), lowerFirst(strings.TrimSuffix(strings.TrimSpace(els), "."))))
		case op["block"] != nil:
			m := op["block"].(map[string]any)
			parts = append(parts, fmt.Sprintf("Block %s.", gatesText(m["gates"])))
		default:
			return "", cdlerr("CDL_RENDER_UNSUPPORTED", "no template for operation form")
		}
	}
	return strings.Join(parts, " "), nil
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func toOpMapSlice(v any) []map[string]any {
	items, ok := v.([]any)
	if !ok {
		if typed, ok := v.([]map[string]any); ok {
			return typed
		}
		return nil
	}
	var out []map[string]any
	for _, item := range items {
		if m, ok := item.(map[string]any); ok {
			out = append(out, m)
		}
	}
	return out
}

func gatesText(v any) string {
	list, ok := v.([]any)
	if !ok {
		if typed, ok := v.([]string); ok {
			list = make([]any, 0, len(typed))
			for _, s := range typed {
				list = append(list, s)
			}
		}
	}
	parts := make([]string, 0, len(list))
	for _, g := range list {
		parts = append(parts, fmt.Sprintf("`%v`", g))
	}
	return strings.Join(parts, ", ")
}

func exprText(v any, ruleTexts map[string]string) (string, error) {
	switch val := v.(type) {
	case string:
		return fmt.Sprintf("`%s`", val), nil
	case bool:
		return fmt.Sprintf("%v", val), nil
	case float64:
		return fmt.Sprintf("%v", val), nil
	case map[string]any:
		switch {
		case val["ref"] != nil:
			ref := fmt.Sprint(val["ref"])
			if id, _, ok := splitRuleRef(ref); ok {
				if text, found := ruleTexts[id]; found {
					return text, nil
				}
			}
			return fmt.Sprintf("`%s`", ref), nil
		case val["op"] != nil:
			if val["op"] == "NOT" {
				e, err := exprText(val["e"], ruleTexts)
				if err != nil {
					return "", err
				}
				return fmt.Sprintf("not %s", e), nil
			}
			l, err := exprText(val["l"], ruleTexts)
			if err != nil {
				return "", err
			}
			r, err := exprText(val["r"], ruleTexts)
			if err != nil {
				return "", err
			}
			switch val["op"] {
			case "==":
				return fmt.Sprintf("%s equals %s", l, r), nil
			case "!=":
				return fmt.Sprintf("%s does not equal %s", l, r), nil
			case "AND":
				return fmt.Sprintf("%s and %s", l, r), nil
			case "OR":
				return fmt.Sprintf("%s or %s", l, r), nil
			default:
				return fmt.Sprintf("%s %v %s", l, val["op"], r), nil
			}
		case val["count"] != nil:
			m := val["count"].(map[string]any)
			if m["where"] != nil {
				w := m["where"].(map[string]any)
				value, err := exprText(w["equals"], ruleTexts)
				if err != nil {
					return "", err
				}
				return fmt.Sprintf("the number of `%v` rows whose `%v` %s", m["table"], w["field"], value), nil
			}
			return fmt.Sprintf("the number of `%v` rows", m["table"]), nil
		case val["hash"] != nil:
			m := val["hash"].(map[string]any)
			return fmt.Sprintf("the hash of `%v`", m["table"]), nil
		case val["available"] != nil:
			return fmt.Sprintf("the `%v` capability is available", val["available"]), nil
		case val["unavailable"] != nil:
			return fmt.Sprintf("the `%v` capability is unavailable", val["unavailable"]), nil
		}
	}
	return "", cdlerr("CDL_RENDER_UNSUPPORTED", "no template for expression form %T", v)
}
