// Package store generates the canonical relational schema for protocol records
// from compiled EIR. It performs no I/O and depends on no SQLite driver; callers
// apply the DDL to a database.
package store

import (
	"fmt"
	"sort"
	"strings"

	"github.com/nckirik/legacy-autopsy/cdl"
)

// SchemaVersion identifies the generated DDL shape.
const SchemaVersion = 1

// Provenance identifies the generated schema.
type Provenance struct {
	Generator         string
	SourceFingerprint string
}

// Schema renders deterministic DDL: one table per declared FIELD block, columns
// from the declared field specs, CHECK constraints for enum-typed columns, and
// append-only triggers for the invocation log.
func Schema(doc *cdl.EIRDoc, prov Provenance) (string, error) {
	enums := map[string][]string{}
	for _, e := range doc.Declarations.Enums {
		enums[e.ID] = e.Values
	}
	var b strings.Builder
	fmt.Fprintf(&b, "-- GENERATED by %s - do not edit\n", prov.Generator)
	fmt.Fprintf(&b, "-- schema-version: %d\n", SchemaVersion)
	fmt.Fprintf(&b, "-- source-fingerprint: %s\n\n", prov.SourceFingerprint)
	b.WriteString("PRAGMA foreign_keys = ON;\n\n")

	specs, err := tableSpecs(doc)
	if err != nil {
		return "", err
	}
	for _, spec := range specs {
		ddl, err := tableDDL(spec.Name, spec.Field, enums)
		if err != nil {
			return "", err
		}
		b.WriteString(ddl)
		b.WriteString("\n")
	}
	return b.String(), nil
}

// tableSpec is one generated table: name plus the declaring FIELD block.
type tableSpec struct {
	Name  string
	Field cdl.EIRField
}

// tableSpecs derives the deterministic table set from the EIR declarations.
func tableSpecs(doc *cdl.EIRDoc) ([]tableSpec, error) {
	seen := map[string]string{}
	specs := make([]tableSpec, 0, len(doc.Declarations.Fields))
	for _, field := range doc.Declarations.Fields {
		name := ident(field.ID)
		if prior, ok := seen[name]; ok {
			return nil, fmt.Errorf("store: tables %q and %q collide as %q", prior, field.ID, name)
		}
		seen[name] = field.ID
		specs = append(specs, tableSpec{Name: name, Field: field})
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	return specs, nil
}

func tableDDL(name string, field cdl.EIRField, enums map[string][]string) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "CREATE TABLE %q (\n", name)
	b.WriteString("  \"la_record_id\" TEXT PRIMARY KEY,\n")
	b.WriteString("  \"la_record_version\" INTEGER NOT NULL DEFAULT 1,\n")
	b.WriteString("  \"la_semantic_fingerprint\" TEXT,\n")
	b.WriteString("  \"la_canonical_payload\" TEXT NOT NULL,\n")
	columnSeen := map[string]string{}
	for _, spec := range field.Fields {
		column := ident(spec.Name)
		if prior, ok := columnSeen[column]; ok {
			return "", fmt.Errorf("store: field %q columns %q and %q collide as %q", field.ID, prior, spec.Name, column)
		}
		columnSeen[column] = spec.Name
		typ := "TEXT"
		if spec.Type == "int" {
			typ = "INTEGER"
		}
		fmt.Fprintf(&b, "  %q %s", column, typ)
		if spec.Required {
			b.WriteString(" NOT NULL")
		}
		if values, ok := enums[spec.Type]; ok {
			quoted := make([]string, 0, len(values))
			for _, v := range values {
				quoted = append(quoted, "'"+strings.ReplaceAll(v, "'", "''")+"'")
			}
			fmt.Fprintf(&b, " CHECK (%q IN (%s))", column, strings.Join(quoted, ", "))
		}
		b.WriteString(",\n")
	}
	b.WriteString("  UNIQUE (\"la_record_id\", \"la_record_version\")\n);\n")
	if strings.EqualFold(field.ID, "INVOCATION-LOG") {
		fmt.Fprintf(&b, "CREATE TRIGGER %q BEFORE UPDATE ON %q BEGIN SELECT RAISE(ABORT, '0G is append-only'); END;\n", name+"_no_update", name)
		fmt.Fprintf(&b, "CREATE TRIGGER %q BEFORE DELETE ON %q BEGIN SELECT RAISE(ABORT, '0G is append-only'); END;\n", name+"_no_delete", name)
	}
	return b.String(), nil
}

func ident(name string) string {
	var b strings.Builder
	lastUnderscore := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastUnderscore = false
		default:
			if !lastUnderscore && b.Len() > 0 {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
	}
	return strings.Trim(b.String(), "_")
}
