// Package store generates the canonical relational schema for protocol records
// from compiled EIR. It performs no I/O and depends on no SQLite driver; callers
// apply the DDL to a database.
package store

import (
	"fmt"
	"sort"
	"strings"

	"github.com/nckirik/legacy-autopsy/cdl"
)

// SchemaVersion identifies the generated DDL shape. Version 2 generates tables
// from declared STORAGE classes instead of one table per FIELD block.
const SchemaVersion = 2

// Provenance identifies the generated schema.
type Provenance struct {
	Generator         string
	SourceFingerprint string
}

// Tables are derived from declared STORAGE classes: record, registry, singleton,
// and log blocks become tables; child, value, and artifact blocks stay embedded
// in their owning payload until the runtime projects them. Declared KEY columns
// become unique natural keys; log blocks get append-only triggers. Relational
// projection of child tables follows the import/export work; see
// docs/relational-mapping.md.
//
// Schema renders deterministic DDL: one table per table-class FIELD block, columns
// from the declared field specs, CHECK constraints for enum-typed columns, and
// append-only triggers for the invocation log. Callers apply it atomically with
// Apply, which wraps the statements in a transaction.
func Schema(doc *cdl.EIRDoc, prov Provenance) (string, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "-- GENERATED by %s - do not edit\n", prov.Generator)
	fmt.Fprintf(&b, "-- schema-version: %d\n", SchemaVersion)
	fmt.Fprintf(&b, "-- source-fingerprint: %s\n\n", prov.SourceFingerprint)
	stmts, err := Statements(doc)
	if err != nil {
		return "", err
	}
	for _, stmt := range stmts {
		b.WriteString(stmt.SQL)
		b.WriteString("\n")
	}
	return b.String(), nil
}

// Statement is one generated DDL object: a table or trigger.
type Statement struct {
	Type string // "table" or "trigger"
	Name string
	SQL  string
}

// Statements returns the generated DDL objects in canonical order: tables sorted
// by name, each followed by its triggers. The order is deterministic and is the
// same order CanonicalDump emits and verifies.
func Statements(doc *cdl.EIRDoc) ([]Statement, error) {
	enums := map[string][]string{}
	for _, e := range doc.Declarations.Enums {
		enums[e.ID] = e.Values
	}
	specs, err := tableSpecs(doc)
	if err != nil {
		return nil, err
	}
	var out []Statement
	for _, spec := range specs {
		stmts, err := tableStatements(spec.Name, spec.Field, enums)
		if err != nil {
			return nil, err
		}
		out = append(out, stmts...)
	}
	return out, nil
}

// tableSpec is one generated table: name plus the declaring FIELD block.
type tableSpec struct {
	Name  string
	Field cdl.EIRField
}

// tableStorageClasses are the declared storage classes that become tables.
var tableStorageClasses = map[string]bool{
	"record":    true,
	"registry":  true,
	"singleton": true,
	"log":       true,
}

// tableSpecs derives the deterministic table set from the declared STORAGE
// classes. Blocks without a recognized class fail closed.
func tableSpecs(doc *cdl.EIRDoc) ([]tableSpec, error) {
	seen := map[string]string{}
	specs := make([]tableSpec, 0, len(doc.Declarations.Fields))
	for _, field := range doc.Declarations.Fields {
		switch field.Storage {
		case "record", "registry", "singleton", "log":
		case "child", "value", "artifact":
			continue
		default:
			return nil, fmt.Errorf("store: field %q declares no usable STORAGE class (got %q)", field.ID, field.Storage)
		}
		name := ident(field.ID)
		if name == "" {
			return nil, fmt.Errorf("store: field %q does not yield a usable table name", field.ID)
		}
		if prior, ok := seen[name]; ok {
			return nil, fmt.Errorf("store: tables %q and %q collide as %q", prior, field.ID, name)
		}
		seen[name] = field.ID
		specs = append(specs, tableSpec{Name: name, Field: field})
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	return specs, nil
}

func tableStatements(name string, field cdl.EIRField, enums map[string][]string) ([]Statement, error) {
	var b strings.Builder
	fmt.Fprintf(&b, "CREATE TABLE %q (\n", name)
	b.WriteString("  \"la_record_id\" TEXT PRIMARY KEY,\n")
	b.WriteString("  \"la_record_version\" INTEGER NOT NULL DEFAULT 1,\n")
	b.WriteString("  \"la_semantic_fingerprint\" TEXT,\n")
	b.WriteString("  \"la_canonical_payload\" TEXT NOT NULL,\n")
	columnSeen := map[string]string{}
	for _, spec := range field.Fields {
		column := ident(spec.Name)
		if column == "" {
			return nil, fmt.Errorf("store: field %q has column %q that does not yield a usable name", field.ID, spec.Name)
		}
		if prior, ok := columnSeen[column]; ok {
			return nil, fmt.Errorf("store: field %q columns %q and %q collide as %q", field.ID, prior, spec.Name, column)
		}
		columnSeen[column] = spec.Name
		typ := "TEXT"
		if spec.Type == "int" {
			typ = "INTEGER"
		}
		fmt.Fprintf(&b, "  %q %s", column, typ)
		if spec.Required {
			b.WriteString(" NOT NULL")
		}
		if values, ok := enums[spec.Type]; ok {
			quoted := make([]string, 0, len(values))
			for _, v := range values {
				quoted = append(quoted, "'"+strings.ReplaceAll(v, "'", "''")+"'")
			}
			fmt.Fprintf(&b, " CHECK (%q IN (%s))", column, strings.Join(quoted, ", "))
		}
		b.WriteString(",\n")
	}
	constraints := []string{"UNIQUE (\"la_record_id\", \"la_record_version\")"}
	if len(field.Key) > 0 {
		quoted := make([]string, len(field.Key))
		for i, key := range field.Key {
			quoted[i] = fmt.Sprintf("%q", ident(key))
		}
		constraints = append(constraints, fmt.Sprintf("UNIQUE (%s)", strings.Join(quoted, ", ")))
	}
	for i, constraint := range constraints {
		b.WriteString("  " + constraint)
		if i == len(constraints)-1 {
			b.WriteString("\n")
		} else {
			b.WriteString(",\n")
		}
	}
	b.WriteString(");")
	out := []Statement{{Type: "table", Name: name, SQL: b.String()}}
	if field.Storage == "log" {
		out = append(out,
			Statement{
				Type: "trigger",
				Name: name + "_no_update",
				SQL:  fmt.Sprintf("CREATE TRIGGER %q BEFORE UPDATE ON %q BEGIN SELECT RAISE(ABORT, '0G is append-only'); END;", name+"_no_update", name),
			},
			Statement{
				Type: "trigger",
				Name: name + "_no_delete",
				SQL:  fmt.Sprintf("CREATE TRIGGER %q BEFORE DELETE ON %q BEGIN SELECT RAISE(ABORT, '0G is append-only'); END;", name+"_no_delete", name),
			},
		)
	}
	return out, nil
}

func ident(name string) string {
	var b strings.Builder
	lastUnderscore := false
	for _, r := range strings.ToLower(name) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastUnderscore = false
		default:
			if !lastUnderscore && b.Len() > 0 {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
	}
	return strings.Trim(b.String(), "_")
}
